name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install system deps (CoolProp needs libboost)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libboost-all-dev
      - name: Install package (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] -q
      - name: Lint (ruff)
        run: ruff check .
      - name: Format (black --check)
        run: black --check .
      - name: Run tests (pytest -q)
        run: pytest -q
